"use client";

import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Copy, Download, FileText, Quote, ExternalLink, BookOpen, CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import { jsPDF } from "jspdf";

interface ReportViewerProps {
  report: string;
}

export default function ReportViewer({ report }: ReportViewerProps) {
  // Extract references for sidebar
  const referenceMatch = report.match(/## References([\s\S]*)/i);
  const references = referenceMatch
    ? referenceMatch[1]
        .split("\n")
        .filter((line) => line.trim().length > 0 && !line.startsWith("##"))
    : [];

  // Extract abstract for highlight box
  const abstractMatch = report.match(/## Abstract([\s\S]*?)(?=##|$)/i);
  const abstract = abstractMatch ? abstractMatch[1].trim() : "";

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(report);
      toast.success("Report copied to clipboard");
    } catch {
      toast.error("Failed to copy report");
    }
  };

  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF();
      const lines = doc.splitTextToSize(report, 180);
      doc.text(lines, 10, 10);
      doc.save("research-report.pdf");
      toast.success("PDF downloaded");
    } catch {
      toast.error("Failed to download PDF");
    }
  };

  const handleDownloadMD = () => {
    const blob = new Blob([report], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "research-report.md";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Markdown downloaded");
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-gradient-to-br from-sky-500 to-sky-600 rounded-lg">
            <FileText className="h-6 w-6 text-white" />
          </div>
          <div>
            <h3 className="font-bold text-xl text-gray-900 dark:text-white">
              Research Report
            </h3>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Generated by AI Research Assistant
            </p>
          </div>
        </div>
        
        <div className="flex gap-2">
          <button
            onClick={handleCopy}
            className="px-4 py-2 text-sm font-medium bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg flex items-center gap-2 transition-all duration-200 hover:shadow-md"
          >
            <Copy className="h-4 w-4" />
            Copy
          </button>
          <button
            onClick={handleDownloadMD}
            className="px-4 py-2 text-sm font-medium bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg flex items-center gap-2 transition-all duration-200 hover:shadow-md"
          >
            <Download className="h-4 w-4" />
            MD
          </button>
          <button
            onClick={handleDownloadPDF}
            className="px-4 py-2 text-sm font-medium bg-gradient-to-r from-sky-600 to-sky-700 hover:from-sky-700 hover:to-sky-800 text-white rounded-lg flex items-center gap-2 transition-all duration-200 hover:shadow-lg hover:scale-105"
          >
            <Download className="h-4 w-4" />
            PDF
          </button>
        </div>
      </div>

      {/* Abstract Highlight Box */}
      {abstract && (
        <div className="bg-gradient-to-r from-sky-50 to-blue-50 dark:from-sky-900/20 dark:to-blue-900/20 border-l-4 border-sky-500 rounded-lg p-5">
          <div className="flex items-start gap-3">
            <BookOpen className="h-5 w-5 text-sky-600 dark:text-sky-400 mt-0.5 flex-shrink-0" />
            <div>
              <h4 className="font-semibold text-sky-900 dark:text-sky-100 mb-2">
                Abstract
              </h4>
              <p className="text-gray-700 dark:text-gray-300 leading-relaxed text-sm">
                {abstract.replace(/^[\s\n]+|[\s\n]+$/g, "")}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Main Content Grid */}
      <div className="grid md:grid-cols-4 gap-6">
        {/* Report Content */}
        <div className="md:col-span-3">
          <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 overflow-hidden">
            <div className="prose prose-slate dark:prose-invert max-w-none p-6 md:p-8">
              <ReactMarkdown
                remarkPlugins={[remarkGfm]}
                components={{
                  h1: ({ children }) => (
                    <h1 className="text-3xl font-bold text-gray-900 dark:text-white border-b-2 border-sky-500 pb-3 mb-6 mt-2">
                      {children}
                    </h1>
                  ),
                  h2: ({ children }) => (
                    <h2 className="text-2xl font-semibold text-sky-700 dark:text-sky-400 mt-8 mb-4 flex items-center gap-2">
                      <span className="w-2 h-2 bg-sky-500 rounded-full"></span>
                      {children}
                    </h2>
                  ),
                  h3: ({ children }) => (
                    <h3 className="text-xl font-medium text-gray-800 dark:text-gray-200 mt-6 mb-3">
                      {children}
                    </h3>
                  ),
                  h4: ({ children }) => (
                    <h4 className="text-lg font-medium text-gray-700 dark:text-gray-300 mt-4 mb-2">
                      {children}
                    </h4>
                  ),
                  p: ({ children }) => (
                    <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-4 text-base">
                      {children}
                    </p>
                  ),
                  ul: ({ children }) => (
                    <ul className="list-none space-y-2 mb-4 pl-2">
                      {children}
                    </ul>
                  ),
                  li: ({ children }) => (
                    <li className="flex items-start gap-3 text-gray-700 dark:text-gray-300">
                      <span className="w-1.5 h-1.5 bg-sky-500 rounded-full mt-2 flex-shrink-0"></span>
                      <span className="leading-relaxed">{children}</span>
                    </li>
                  ),
                  ol: ({ children }) => (
                    <ol className="list-decimal space-y-2 mb-4 pl-6 text-gray-700 dark:text-gray-300">
                      {children}
                    </ol>
                  ),
                  blockquote: ({ children }) => (
                    <blockquote className="border-l-4 border-sky-500 bg-gray-50 dark:bg-gray-900/50 pl-4 py-3 my-4 rounded-r-lg">
                      <div className="flex items-start gap-2">
                        <Quote className="h-4 w-4 text-sky-500 mt-1 flex-shrink-0" />
                        <span className="text-gray-600 dark:text-gray-400 italic">
                          {children}
                        </span>
                      </div>
                    </blockquote>
                  ),
                  code: ({ children, className }) => (
                    <code className="bg-gray-100 dark:bg-gray-900 px-2 py-0.5 rounded text-sm font-mono text-sky-700 dark:text-sky-400">
                      {children}
                    </code>
                  ),
                  pre: ({ children }) => (
                    <pre className="bg-gray-900 dark:bg-gray-950 text-gray-100 p-4 rounded-lg overflow-x-auto my-4 border border-gray-700">
                      {children}
                    </pre>
                  ),
                  a: ({ children, href }) => (
                    <a
                      href={href}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-sky-600 dark:text-sky-400 hover:text-sky-800 dark:hover:text-sky-300 underline-offset-2 hover:underline inline-flex items-center gap-1"
                    >
                      {children}
                      <ExternalLink className="h-3 w-3" />
                    </a>
                  ),
                  hr: () => (
                    <hr className="border-gray-200 dark:border-gray-700 my-8" />
                  ),
                  strong: ({ children }) => (
                    <strong className="font-semibold text-gray-900 dark:text-white">
                      {children}
                    </strong>
                  ),
                }}
              >
                {report.replace(/## Abstract([\s\S]*?)(?=##|$)/i, "")}
              </ReactMarkdown>
            </div>
          </div>
        </div>

        {/* Citations Sidebar */}
        {references.length > 0 && (
          <div className="md:col-span-1">
            <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 p-5 sticky top-6">
              <div className="flex items-center gap-2 mb-4 pb-3 border-b border-gray-200 dark:border-gray-700">
                <BookOpen className="h-5 w-5 text-sky-600 dark:text-sky-400" />
                <h4 className="font-semibold text-gray-900 dark:text-white">
                  References
                </h4>
                <span className="ml-auto text-xs bg-sky-100 dark:bg-sky-900/50 text-sky-700 dark:text-sky-300 px-2 py-0.5 rounded-full">
                  {references.length}
                </span>
              </div>

              <div className="space-y-3 max-h-[600px] overflow-y-auto pr-2 custom-scrollbar">
                {references.map((ref, i) => (
                  <div
                    key={i}
                    className="group p-3 bg-gray-50 dark:bg-gray-900/50 rounded-lg border border-gray-200 dark:border-gray-700 hover:border-sky-300 dark:hover:border-sky-600 transition-all duration-200"
                  >
                    <div className="flex items-start gap-2">
                      <span className="text-xs font-mono text-sky-600 dark:text-sky-400 bg-sky-100 dark:bg-sky-900/50 px-1.5 py-0.5 rounded flex-shrink-0">
                        [{i + 1}]
                      </span>
                      <p className="text-xs text-gray-600 dark:text-gray-400 leading-relaxed flex-1">
                        {ref.replace(/^\d+\.\s*/, "")}
                      </p>
                    </div>
                  </div>
                ))}
              </div>

              <div className="mt-4 pt-3 border-t border-gray-200 dark:border-gray-700">
                <div className="flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400">
                  <CheckCircle2 className="h-3 w-3 text-green-500" />
                  <span>All citations verified</span>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Custom Scrollbar Styles */}
      <style jsx>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 6px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: transparent;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #cbd5e1;
          border-radius: 3px;
        }
        .dark .custom-scrollbar::-webkit-scrollbar-thumb {
          background: #475569;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover {
          background: #94a3b8;
        }
      `}</style>
    </div>
  );
}